/**
 * Tharwati icon system — Phosphor geometry (MIT), drawn with react-native-svg.
 *
 * Default weight is DUOTONE: a crisp line plus a soft 20 % fill of the same
 * colour — richer than plain outlines, calmer than solid glyphs, and a quiet
 * match for the emerald/gold identity. `regular` (line only) is used for
 * small UI chrome. Path data lives in iconPaths.ts (generated by
 * scripts/gen-icons.py), so only the icons below ship in the bundle.
 *
 * Screens use SEMANTIC names (`edit`, `warning`, `catFood`…), never library
 * names. Directional icons mirror automatically in right-to-left layouts.
 */
import Svg, { G, Path } from 'react-native-svg';

import { ICON_PATHS } from './iconPaths';

export type IconName = keyof typeof ICON_PATHS;
export type IconWeight = 'duotone' | 'regular';

/** Icons that point along the reading direction and must flip in RTL. */
const DIRECTIONAL: ReadonlySet<IconName> = new Set<IconName>(['forward', 'back', 'income', 'expense']);

/** Category icons in database `iconCode` order (0..11). */
export const CATEGORY_ICON_NAMES: readonly IconName[] = [
  'catHousing',
  'catFood',
  'catTransport',
  'catUtilities',
  'catTelecom',
  'catHealth',
  'catEducation',
  'catFamily',
  'catShopping',
  'catEntertainment',
  'catDebt',
  'catOther',
];

export function PhIcon({
  name,
  size = 22,
  color,
  weight = 'duotone',
  rtl = false,
  fillOpacity = 0.2,
}: {
  name: IconName;
  size?: number;
  color: string;
  weight?: IconWeight;
  rtl?: boolean;
  /** Opacity of the duotone fill layer. */
  fillOpacity?: number;
}) {
  const icon = ICON_PATHS[name];
  const mirrored = rtl && DIRECTIONAL.has(name);
  return (
    <Svg
      width={size}
      height={size}
      viewBox="0 0 256 256"
      style={mirrored ? { transform: [{ scaleX: -1 }] } : undefined}
      accessibilityElementsHidden
      importantForAccessibility="no"
    >
      <G fill={color}>
        {weight === 'duotone' ? (
          <>
            {icon.f.map((d, i) => (
              <Path key={`f${i}`} d={d} opacity={fillOpacity} />
            ))}
            {icon.l.map((d, i) => (
              <Path key={`l${i}`} d={d} />
            ))}
          </>
        ) : (
          icon.r.map((d, i) => <Path key={i} d={d} />)
        )}
      </G>
    </Svg>
  );
}
